import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getSessionProfile } from '@/lib/auth';
import { signOut, updateMyProfile } from '@/app/server-actions';
export default async function Pending({searchParams}:{searchParams:Promise<{error?:string;saved?:string}>}){
 const {user,profile}=await getSessionProfile(); if(!user) redirect('/login'); const p=await searchParams;
 if(!profile) return <main className="wrap"><section className="form-card"><h1>Đang khởi tạo hồ sơ</h1><p className="muted">Hãy tải lại trang sau ít phút. Nếu vẫn gặp lỗi, kiểm tra SQL migration và trigger trong Supabase.</p></section></main>;
 return <main className="wrap"><section className="form-card" style={{maxWidth:720}}><div className="eyebrow">MEMBER CONSOLE</div><h1>Hồ sơ của {profile.display_name}</h1><p className={profile.status==='approved'?'success':'notice'}>{profile.status==='approved'?'Tài khoản đã được duyệt. Bạn có thể chỉnh sửa hồ sơ của mình.':profile.status==='rejected'?'Đơn gia nhập chưa được chấp nhận. Liên hệ Tông chủ nếu cần làm rõ.':'Đơn gia nhập đang chờ Tông chủ xem xét. Các khu vực thành viên vẫn bị khóa.'}</p>{p.error&&<p className="error">{p.error}</p>}{p.saved&&<p className="success">Đã lưu hồ sơ.</p>}{profile.status==='approved'&&<form action={updateMyProfile}><div className="field"><label>Tên hiển thị</label><input name="display_name" required minLength={2} maxLength={40} defaultValue={profile.display_name}/></div><div className="field"><label>Minecraft username</label><input name="minecraft_username" maxLength={32} defaultValue={profile.minecraft_username??''}/></div><div className="field"><label>Discord username</label><input name="discord_username" maxLength={80} defaultValue={profile.discord_username??''}/></div><div className="field"><label>URL ảnh đại diện (tùy chọn)</label><input name="avatar_url" type="url" maxLength={500} defaultValue={profile.avatar_url??''} placeholder="https://..."/></div><div className="field"><label>Giới thiệu</label><textarea name="bio" maxLength={400} rows={3} defaultValue={profile.bio??''}/></div><button className="btn" type="submit">Lưu hồ sơ</button> <Link className="btn secondary" href="/members">Xem thành viên</Link></form>}{profile.status!=='approved'&&<p className="muted">Bạn vẫn có thể đăng xuất trong thời gian chờ.</p>}<form action={signOut} style={{marginTop:18}}><button className="btn secondary" type="submit">Đăng xuất</button></form></section></main>
}
